# Generated by Django 6.0 on 2025-12-28 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('destacada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Joya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=1)),
                ('peso_gramos', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria_nombre', models.CharField(blank=True, max_length=50)),
                ('material_nombre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('quilates', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
